# Generated by Django 4.0.6 on 2022-08-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
            options={
                'ordering': ['agregado'],
            },
        ),
    ]
