# Generated by Django 4.0.6 on 2022-08-28 23:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
